import pygame
RADIUS = 100

# WIDTH, HEIGHT = 750, 750
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
CHECKBOX_SIZE = 30
CHECKBOX_MARGIN = 5
NUM_ROWS = 3
NUM_COLS = 21
CHECKBOX_WIDTH = NUM_COLS * CHECKBOX_SIZE + (NUM_COLS - 1) * CHECKBOX_MARGIN
CHECKBOX_HEIGHT = NUM_ROWS * CHECKBOX_SIZE + (NUM_ROWS - 1) * CHECKBOX_MARGIN


BUTTON_WIDTH = 100
BUTTON_HEIGHT = 40
BUTTON_COLOR = (0, 150, 0)  # Green
BUTTON_TEXT_COLOR = WHITE
BUTTON_TEXT = "Reset game"
BUTTON_FONT_SIZE = 20

def init():
    global WIN, WIDTH, HEIGHT
    WIN = pygame.display.get_surface()
    WIDTH, HEIGHT = WIN.get_size()

# init()
# print(WIN)